### ISSUE TITLE
Error running sf2 example

### ISSUE THREAD

**Issue by alex404** [alex-petrenko/sample-factory#205]
Hello, sorry if I'm doing something silly, but I set up a conda environment for sf2, and am trying to run the vizdoom training examples.

If I run
`python -m sf_examples.vizdoom_examples.train_vizdoom --env=doom_battle --train_for_env_steps=4000000000 --algo=APPO --env_frameskip=4 --use_rnn=True --num_workers=72 --num_envs_per_worker=8 --num_policies=1 --batch_size=2048 --wide_aspect_ratio=False --max_grad_norm=0.0 --experiment=doom_battle`

then the program crashes with
```
Traceback (most recent call last):
  File "/home/alex404/.miniconda3/envs/sf2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/alex404/.miniconda3/envs/sf2/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/alex404/temporary/retinal-rl/sample-factory/sf_examples/vizdoom_examples/train_vizdoom.py", line 4, in <module>
    from sample_factory.algo.utils.context import global_model_factory
  File "/home/alex404/temporary/retinal-rl/sample-factory/sample_factory/algo/utils/context.py", line 3, in <module>
    from sample_factory.model.model_factory import ModelFactory
  File "/home/alex404/temporary/retinal-rl/sample-factory/sample_factory/model/model_factory.py", line 3, in <module>
    from sample_factory.model.actor_critic import ActorCritic, default_make_actor_critic_func
  File "/home/alex404/temporary/retinal-rl/sample-factory/sample_factory/model/actor_critic.py", line 8, in <module>
    from sample_factory.algo.utils.action_distributions import is_continuous_action_space, sample_actions_log_probs
  File "/home/alex404/temporary/retinal-rl/sample-factory/sample_factory/algo/utils/action_distributions.py", line 3, in <module>
    import gym
  File "/home/alex404/.miniconda3/envs/sf2/lib/python3.10/site-packages/gym/__init__.py", line 15, in <module>
    from gym.envs import make, spec, register
  File "/home/alex404/.miniconda3/envs/sf2/lib/python3.10/site-packages/gym/envs/__init__.py", line 5, in <module>
    _load_env_plugins()
  File "/home/alex404/.miniconda3/envs/sf2/lib/python3.10/site-packages/gym/envs/registration.py", line 283, in load_env_plugins
    for plugin in metadata.entry_points(group=entry_point):
  File "/home/alex404/.miniconda3/envs/sf2/lib/python3.10/importlib/metadata/__init__.py", line 1009, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/home/alex404/.miniconda3/envs/sf2/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "/home/alex404/.miniconda3/envs/sf2/lib/python3.10/importlib/metadata/__init__.py", line 1006, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/home/alex404/.miniconda3/envs/sf2/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/home/alex404/.miniconda3/envs/sf2/lib/python3.10/importlib/metadata/__init__.py", line 941, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "/home/alex404/.miniconda3/envs/sf2/lib/python3.10/importlib/metadata/__init__.py", line 622, in _normalized_name
    return Prepared.normalize(self.name)
  File "/home/alex404/.miniconda3/envs/sf2/lib/python3.10/importlib/metadata/__init__.py", line 871, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/home/alex404/.miniconda3/envs/sf2/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

Any tips for how I can get around this? Thanks!

**Comment by alex-petrenko** [comment]
Hi @alex404 

This is a rather extreme configuration meant for a large server (note 72 workers)
Running as many workers as you have logical CPU cores (threads) is a good heuristic.

I.e. on my laptop the following runs fine (I have 6-core CPU with hyperthreading so I use 12 workers):

```
python -m sf_examples.vizdoom_examples.train_vizdoom --env=doom_battle --train_for_env_steps=4000000000 --algo=APPO --env_frameskip=4 --use_rnn=True --num_workers=12 --num_envs_per_worker=10 --num_policies=1 --batch_size=2048 --wide_aspect_ratio=False --max_grad_norm=0.0 --experiment=doom_battle
```

If it's still crashing, check RAM and VRAM usage, are you well within limits?

**Comment by alex-petrenko** [comment]
Also, your error might be completely unrelated.
There were recent changes in OpenAI Gym, update to 0.26 broke a bunch of APIs. 

Apparently they also had some issue with importlib which should be fixed in the latest release.

I'd suggest removing `gym` and reinstalling `pip install -e .` in sample factory root to pull the newest dependencies.
Or even reinstalling your entire python/conda env from scratch if you still have the issue. It should work because there are no issues on my machine and CI tests run fine as well.

@edbeeching probably knows more about this :)

**Comment by alex404** [comment]
I tried running that command but see no difference. The program doesn't even start - it crashes immediately, so it doesn't tax any of my resources at all (though I have a relatively beefy home computer: 64G RAM and 24G VRAM)

**Comment by alex404** [comment]
Okay, that makes sense. I noticed big changes around the newest gym releases. Should I revert any of your recent sf2 commits e.g. around gym?

**Comment by alex-petrenko** [comment]
I'd suggest you use the latest version of sf2 code from sf2 branch and gym 0.26.2 (latest version).
The latest code is fully integrated with the new Gym API so everything should work.

The error you have looks like a dependency issue probably not even related to Sample Factory.
As you can see, the error happens as soon as you `import gym`

Try to create an empty file that just has `import gym` in it and see if that works. It should be easier to debug.
If after reinstalling Python dependencies the issue persists, I suggest you ask on Gym github.

**Comment by alex404** [comment]
Okay, so the problem was that I was installing sf2 from source with `python setup.py build && python setup.py install` rather than `pip install .`. Oddly enough, when I first installed the latest `gym`, I could execute `import gym` just fine, but after incorrectly installing sf2 it would cause `import gym` statement to throw the error, even outside of any sf2 code.

Sorry if this was a novice mistake. I'll close the issue.
